#include "marauder_gui_app_i.h"
#include <string.h>
#include <stdlib.h>
#include <storage/storage.h>

/* generated by fbt from .png files in images folder */
#include <marauder_gui_icons.h>

#define MARAUDER_TICK_PERIOD_MS 100

/* One byte, persisted across reboots so the user only has to pick a language once. Missing file
   (first run, or an older version without this feature) just leaves app->language at its
   zero-initialized default (MarauderLanguageTurkish). */
void marauder_gui_load_language(MarauderGuiApp* app) {
    Storage* storage = furi_record_open(RECORD_STORAGE);
    File* file = storage_file_alloc(storage);

    if(storage_file_open(file, APP_DATA_PATH("language.bin"), FSAM_READ, FSOM_OPEN_EXISTING)) {
        uint8_t value = MarauderLanguageTurkish;
        if(storage_file_read(file, &value, sizeof(value)) == sizeof(value)) {
            app->language = (value == MarauderLanguageEnglish) ? MarauderLanguageEnglish :
                                                                  MarauderLanguageTurkish;
        }
    }

    storage_file_close(file);
    storage_file_free(file);
    furi_record_close(RECORD_STORAGE);
}

void marauder_gui_save_language(MarauderGuiApp* app) {
    Storage* storage = furi_record_open(RECORD_STORAGE);
    File* file = storage_file_alloc(storage);

    if(storage_file_open(file, APP_DATA_PATH("language.bin"), FSAM_WRITE, FSOM_CREATE_ALWAYS)) {
        uint8_t value = (uint8_t)app->language;
        storage_file_write(file, &value, sizeof(value));
    }

    storage_file_close(file);
    storage_file_free(file);
    furi_record_close(RECORD_STORAGE);
}

static bool marauder_gui_custom_event_callback(void* context, uint32_t event) {
    MarauderGuiApp* app = context;
    return scene_manager_handle_custom_event(app->scene_manager, event);
}

static bool marauder_gui_navigation_event_callback(void* context) {
    MarauderGuiApp* app = context;
    return scene_manager_handle_back_event(app->scene_manager);
}

/* Drains bytes received over UART since the last tick, reassembles them into lines, and
   forwards each complete line to whichever scene currently wants them (if any). Runs on the
   ViewDispatcher's own thread, so it is safe to touch view/model state directly here. */
static void marauder_gui_tick_event_callback(void* context) {
    MarauderGuiApp* app = context;

    uint8_t buf[64];
    size_t received;

    while((received = marauder_uart_receive(app->uart, buf, sizeof(buf))) > 0) {
        for(size_t i = 0; i < received; i++) {
            char c = (char)buf[i];

            if(c == '\r') continue;

            if(c == '\n') {
                app->rx_line_buf[app->rx_line_len] = '\0';
                if(app->rx_line_len > 0 && app->uart_line_handler) {
                    app->uart_line_handler(app, app->rx_line_buf);
                }
                app->rx_line_len = 0;
            } else if(app->rx_line_len < MARAUDER_LINE_MAX - 1) {
                app->rx_line_buf[app->rx_line_len++] = c;
            }
        }
    }

    if(app->tick_handler) {
        app->tick_handler(app);
    }
}

static MarauderGuiApp* marauder_gui_app_alloc(void) {
    MarauderGuiApp* app = malloc(sizeof(MarauderGuiApp));
    memset(app, 0, sizeof(MarauderGuiApp));

    app->selected_ap_index = -1;
    app->selected_tracker_index = -1;
    app->selected_probe_index = -1;
    app->selected_ip_index = -1;

    marauder_gui_load_language(app);

    app->uart = marauder_uart_alloc();

    app->gui = furi_record_open(RECORD_GUI);

    app->view_dispatcher = view_dispatcher_alloc();
    app->scene_manager = scene_manager_alloc(&marauder_gui_scene_handlers, app);

    view_dispatcher_set_event_callback_context(app->view_dispatcher, app);
    view_dispatcher_set_custom_event_callback(
        app->view_dispatcher, marauder_gui_custom_event_callback);
    view_dispatcher_set_navigation_event_callback(
        app->view_dispatcher, marauder_gui_navigation_event_callback);
    view_dispatcher_set_tick_event_callback(
        app->view_dispatcher, marauder_gui_tick_event_callback, MARAUDER_TICK_PERIOD_MS);

    app->widget = widget_alloc();
    view_dispatcher_add_view(
        app->view_dispatcher, MarauderGuiViewWidget, widget_get_view(app->widget));

    app->wifi_list_view = marauder_gui_wifi_list_view_alloc(app);
    view_dispatcher_add_view(app->view_dispatcher, MarauderGuiViewWifiList, app->wifi_list_view);

    app->number_input = number_input_alloc();
    view_dispatcher_add_view(
        app->view_dispatcher, MarauderGuiViewNumberInput, number_input_get_view(app->number_input));

    app->text_input = text_input_alloc();
    view_dispatcher_add_view(
        app->view_dispatcher, MarauderGuiViewTextInput, text_input_get_view(app->text_input));

    app->menu_view = marauder_gui_menu_view_alloc(app);
    view_dispatcher_add_view(app->view_dispatcher, MarauderGuiViewMenu, app->menu_view);

    app->attack_status_view = marauder_gui_attack_view_alloc(app);
    view_dispatcher_add_view(
        app->view_dispatcher, MarauderGuiViewAttackStatus, app->attack_status_view);

    return app;
}

static void marauder_gui_app_free(MarauderGuiApp* app) {
    view_dispatcher_remove_view(app->view_dispatcher, MarauderGuiViewWidget);
    widget_free(app->widget);

    view_dispatcher_remove_view(app->view_dispatcher, MarauderGuiViewWifiList);
    view_free(app->wifi_list_view);

    view_dispatcher_remove_view(app->view_dispatcher, MarauderGuiViewNumberInput);
    number_input_free(app->number_input);

    view_dispatcher_remove_view(app->view_dispatcher, MarauderGuiViewTextInput);
    text_input_free(app->text_input);

    view_dispatcher_remove_view(app->view_dispatcher, MarauderGuiViewMenu);
    view_free(app->menu_view);

    view_dispatcher_remove_view(app->view_dispatcher, MarauderGuiViewAttackStatus);
    view_free(app->attack_status_view);

    scene_manager_free(app->scene_manager);
    view_dispatcher_free(app->view_dispatcher);

    furi_record_close(RECORD_GUI);

    marauder_uart_free(app->uart);

    free(app);
}

int32_t marauder_gui_app(void* p) {
    UNUSED(p);

    MarauderGuiApp* app = marauder_gui_app_alloc();

    view_dispatcher_attach_to_gui(app->view_dispatcher, app->gui, ViewDispatcherTypeFullscreen);

    scene_manager_next_scene(app->scene_manager, MarauderGuiSceneMainMenu);

    view_dispatcher_run(app->view_dispatcher);

    marauder_gui_app_free(app);

    return 0;
}
